spring.application.name = backend

spring.datasource.url=jdbc:postgresql://localhost:5432/bookit
spring.datasource.username=postgres
spring.datasource.password=balaji@06
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true




spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=9f8d7b3a1e2c4b5a6f7e8d9c0b1a2f3e4d5c6b7a8f9e0d1c2b3a4f5e6d7c8b9a
jwt.expiration=3600000