spring.application.name = backend

# MySQL Connection URL
spring.datasource.url = jdbc:mysql://localhost:3306/bookit?useSSL=false&serverTimezone=UTC

# Credentials
spring.datasource.username = root
spring.datasource.password = balaji@06
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate Configuration
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
# Automatically creates/updates tables based on Java classes
spring.jpa.hibernate.ddl-auto=update
# Logs SQL queries to the console
spring.jpa.show-sql=true